### ISSUE TITLE
Not Showing the type errors

### ISSUE THREAD

**Issue by vijaykrishnaabba7** [ssricardo/anki-plugins#109]
Everything is working fine here

![1](https://user-images.githubusercontent.com/94542271/152526374-d99c9f2b-fe04-4f40-ba90-7afe2d9484da.jpeg) 
                                 Take a look at this.
                                           
![3_Trim](https://user-images.githubusercontent.com/94542271/152526416-9be9fcdb-6024-42f5-9974-5821f7ab6d9f.gif)

With normal text errors and the correct answer is displayed,
**However, when using the syntax highlighter addon on text, incorrect text is not displayed.**
syntax highlighter addon:  https://ankiweb.net/shared/info/1463041493 

Thank you for your excellent add-on 
These past few months I have been looking for this kind of add-on, 
Google, on the other hand, always shows the Multi-Line Type Answer Box add-on which only works on basic cards. I preferred to search with multiple lines rather than multiple types, but I finally found it.
Thank you so much.

**Comment by lightmotive** [comment]
@ssricardo, I found this issue because the add-on doesn't work properly any time the answer contains HTML as in vijaykrishnaabba7's non-working example above, including character codes like `&nbsp;`, `&gt;`, `&lt;`, `&amp;`, etc.

I quickly scanned your code and noticed the `original_clear_correct_value` function in **handler.py** should strip HTML on line 238 (`cor = stripHTML(cor)`), so perhaps `stripHTML` is not working properly or as you had expected. Or maybe there's an unnecessary double-conversion somewhere. Another case to consider: is Anki processing the typed answer in a way your code doesn't expect?

I would offer to help, but I don't have experience with Anki add-on development or Python yet. That may change in the future, at which time I would create some unit tests to catch issues like this. In the meantime, I very much appreciate your efforts with this add-on. It is essential to my recall practice, as well.

**Comment by ssricardo** [comment]
Addressed in version 2.7 (10.01.2023)
