### ISSUE TITLE
Fill in the blanks: It gives false wrongs 

### ISSUE THREAD

**Issue by Cristinasj** [ssricardo/anki-plugins#111]
![image](https://user-images.githubusercontent.com/56409822/154838690-43b5c055-9f90-4748-9708-8a60892525d8.png)

I wrote what I was supposed to write and it recognized it as wrong

**Comment by ssricardo** [comment]
That's odd. 
Did you copy/paste the text from some website directly? I'm wondering whether there's some hidden character.

Could you also try without the : and the "?

**Comment by lightmotive** [comment]
I see this problem frequently--it's usually due to a hidden `&nbsp;` within the cloze delimiters, which Anki often adds when changing formatting of highlighted text. You can replace those `&nbsp;` codes with a regular space using the HTML view (Shift + Cmd/Ctrl + X)--I realize that's not the most user-friendly, but it usually resolves the issue.

Perhaps the add-on can eventually replace `&nbsp;` in the expected answer with a "normal" space before comparing it with the typed answer (assuming the typed answer only contains normal spaces).

**Comment by ssricardo** [comment]
Mostly it was user error, but anyway an additional handling the input data was added in the new version:
Addressed in version 2.7 (10.01.2023)
