### ISSUE TITLE
Fill the blanks: Changing feedback on "Show answer"

### ISSUE THREAD

**Issue by kurkasr** [ssricardo/anki-plugins#127]
Could you change feedback after answering card like this 
![image](https://user-images.githubusercontent.com/120309744/211937600-4dcead9e-cd5b-438d-92bc-d8040136d563.png)
instead of 
![image](https://user-images.githubusercontent.com/120309744/211937713-43635eb4-b83f-48e7-9dd0-51f0770c4d5c.png)?

**Comment by ssricardo** [comment]
Hey!

Unfortunately, I don't think this fits well with this add-on. 

This is exactly about having the input fields inline. Then possibly having multiple of them in middle of a text. 
That display (like standard Anki) would break the flow of the text.

What I do plan to do, is supporting a distinct prefix for this add-on. So that, it would be possible to have it only for some note-type and still keep the standard Anki (like you asked) for other note-types. 
I think there's an open issue about that already...
