### ISSUE TITLE
Check focus on fill-the-blank

### ISSUE THREAD

**Issue by ssricardo** [ssricardo/anki-plugins#19]
Check whether the focus on first field is working.
From a comment on ankiweb:

> Very convenient and useful add-on! Can only recommend. Many thanks for the work! Only one request. Could you please improve the add-on so, that the cursor focuses on the first field for the answer?

**Comment by ssricardo** [comment]
Do you have the latest version of this addon?
What is your environment (Operational system and Anki version)?

**Comment by and-riy** [comment]
System: Xubuntu 18.10
"Fill the blanks" v1.2
Anki v2.1.13
When I launch Anki from terminal, with each card where "Fill the blanks" is used, in the terminal occurs an error:
`JS error on line 1: Uncaught ReferenceError: focusOnFirst is not defined`

**Comment by ssricardo** [comment]
It seems the addon couldn't load when you started your reviewer. 
It may be duo to other addon that overrides the setup.

What other addons do you use?

**Comment by and-riy** [comment]
I've reinstalled all addons one by one. It turned out that "fill-the-blank" no longer focuses on the first field after installing ["Cookie monster"](https://ankiweb.net/shared/info/1501583548) (which is required for ["Insert Randomized Lists"](https://ankiweb.net/shared/info/1280092568)).

**Comment by ssricardo** [comment]
@and-riy 
If you can, look up "_initWeb" on "Cookie monster" code. It probably overrides that function ignoring both the default code (anki) and other addons (like fill-the-blank).

I'm closing the issue as it's a problem on other addon (instead of this), ok?!

**Comment by and-riy** [comment]
The combination of "Cookie Monster" with other installed addons (over 10) does not cause problems, so I would not say that _"it's a problem on another addon (instead of this)"_.
Unfortunately, I'm not familiar with code [of "Cookie Monster" or "fill-the-blank"], and therefore I to bother you with my modest request to make your application a little bit more convenient (for "Cookie Monster" users and all addons that require it, for example "Insert Randomized Lists").
So, your suggestion, in its present form, seems to me to be a choice: to get used to the inconvenience of the addon "Fill the blanks", or to abandon it.

P.S. I have not found any mention of "_initWeb" in any file associated with "Cookie monster".

**Comment by ssricardo** [comment]
Ok. I'll install Cookie Monster and try to review its code. 
I'll let you know if I find anything useful...

**Comment by ssricardo** [comment]
It's indeed incompatible with the way the other addon works.

if you open the script (py file) from *Cookie Monster*, there is a part:
`AnkiWebPage.setHtml = setHtmlWithBaseurl`

This means it changes the *setHtml* function from Anki.
Checking Anki's code: [webview.py](https://github.com/dae/anki/blob/master/aqt/webview.py), we find that *setHtml*.  
And this function exactly is the responsible for *setFocus* (line 187).

Therefore, Anki doesn't send the focus and *Fill the blanks* never receives it.  

Sorry but it's out of my hands.

Closing, as there is nothing to be done on this addon.
