### ISSUE TITLE
[Web Browser] Duck Duck Go Image Import

### ISSUE THREAD

**Issue by ghost** [ssricardo/anki-plugins#20]
Hello.
In Duckduckgo both the expanded image and the view file button contain direct links to the image in a standard browser
![image](https://user-images.githubusercontent.com/13769570/58741923-c4f04500-840e-11e9-90f5-655b17dfd58d.png)
 yet the addon throws the following error message.
![image](https://user-images.githubusercontent.com/13769570/58741903-8ce90200-840e-11e9-9d71-65b509aca16f.png)

**Comment by ssricardo** [comment]
Hi! I'll try to check it out.

If you copy that URL and paste it into Anki Editor, does it import the image? Or it just pastes the URL as is?!

**Comment by ghost** [comment]
Sorry for the late reply. 
Yeah, it pastes perfect.

**Comment by ssricardo** [comment]
In this situation, if you click "Yes", does it get to download the image?

**Comment by ghost** [comment]
No. It throws the following error.
![image](https://user-images.githubusercontent.com/13769570/59550603-0b3fbb00-8f5c-11e9-8640-ee26f24b43ce.png)

**Comment by ssricardo** [comment]
For some reason, when opened on that web browser, the website adds a suffix "&f=1".
That's why it can download from there.

The URL is shown now, from version **1.3**.

For a while, since the URL isn't finished as expected by Anki, the behavior is the expected. Therefore I'm closing this issue, ok?!

In the future I'll make this importing feature independent of Anki.
