### ISSUE TITLE
Feature request: Fill the blanks

### ISSUE THREAD

**Issue by rezaemortaza** [ssricardo/anki-plugins#96]
Hi,

Thank you for developing the Fill the blanks plugins. It is great!

Have you considered making the add-on compatible with Cloze Overlapper. I think learning how to code would be more effective if it is done in the style of Cloze Overlapper, where a code block is revised in a sequential order and the previous line serves as the context cue for the next.

Thanks.

**Comment by ssricardo** [comment]
Note for later: Also consider _Edit Field During Review (Cloze)_ (from comment on AnkiWeb)

I'll try addressing this later, BUT I can say in advance that's probably quite complicate. Because I might need to reference code from other add-ons, then it become very hard to maintain (changes on the other add-ons could break this), and there will  be people asking the same for multiple distinct add-ons. 

So again, I can give it a try but please don't be so optimistic about it.

**Comment by rafaelsb0** [comment]
Opa @ssricardo, tudo bem? O seu add-on é sensacional. Melhorou muito o meu estudo no Anki. Muito obrigado pelo add-on e pela ajuda.

Se tiver como fazer os dois add-ons funcionarem juntos (Fill the blanks e  Edit Field During Review(Cloze)) e apenas me enviar as modificações para que eu altere na pasta do add-on do meu Anki já é suficiente. Fui o único que pedi essa modificação (os dois comentários no ankiweb) e aparentemente é um problema que apenas eu estou tendo. Talvez adicionar para todos os usuários possa gerar problemas de compatibilidade no futuro.

Sobre aquele primeiro teste que fizemos:

Inseri o código que você me passou no arquivo do add-on e coloquei {{edit:type:cloze:Texto}} no cartão. 

Quando abri o card para revisar, não apareceu o texto, apenas isso: https://imgur.com/a/6epawRt . Porém, foi possível editar o texto completo ao clicar (control+click), que é o atalho do edit field. Apareceu o texto todo e foi possível modificar. Nessa parte funcionou. Porém como falei anteriormente, ao voltar para a revisão, apenas aparece [[type:Texto]].

**Comment by ssricardo** [comment]
A change was made to make it better compatible with other add-ons.
Please check the new version: version 2.7 (10.01.2023). 

If something else is still needed here, reopen later.
